import { useMemo, useState } from "react";
import { FileDropzone } from "./FileDropzone";
import { Button } from "./Button";
import { Badge } from "./Badge";
import { SpatialGisCore } from "../helpers/SpatialGisCore";
import { SPATIAL_ANALYSIS_PRESETS, assignDatasetRoles, buildCanonicalAnalysisReceipt, buildSpatialDatasets, buildUploadManifest, evaluatePresetEligibility, type AnalysisPresetId, type ParserEvidence, type SpatialDatasetRole, type UploadManifest } from "../helpers/spatialDatasetWorkflow";

const accepted=".geojson,.json,.kml,.csv,.shp,.shx,.dbf,.prj,.cpg,.zip,.kmz,.tif,.tiff,.gpkg";

async function sha256(file:File):Promise<string|null>{try{if(!globalThis.crypto?.subtle)return null;const digest=await globalThis.crypto.subtle.digest("SHA-256",await file.arrayBuffer());return Array.from(new Uint8Array(digest)).map(byte=>byte.toString(16).padStart(2,"0")).join("")}catch{return null}}
function duplicates(values:string[]){const seen=new Set<string>(),duplicate=new Set<string>();values.forEach(value=>{if(seen.has(value))duplicate.add(value);else seen.add(value)});return[...duplicate].sort()}
async function readFileText(file:File):Promise<string>{
 const candidate=file as File&{text?:()=>Promise<string>};
 if(typeof candidate.text==="function")return candidate.text();
 return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error??new Error("Unable to read file."));reader.onload=()=>resolve(String(reader.result??""));reader.readAsText(file)});
}
async function parserEvidence(file:File,sourceManifestationId:string):Promise<ParserEvidence|null>{
 const lower=file.name.toLowerCase();if(![".geojson",".json",".kml",".csv"].some(suffix=>lower.endsWith(suffix)))return null;
 const parsed=SpatialGisCore.parseFileText(file.name,await readFileText(file));if(!parsed.ok)return{sourceManifestationId,parser:"SpatialGisCore/v1",state:"FAIL",error:parsed.error};
 const ids=parsed.collection.features.map(feature=>String(feature.id??"")).filter(Boolean),geometryTypes=[...new Set(parsed.collection.features.map(feature=>feature.geometry.type))].sort();
 const hasTerrain=parsed.collection.features.some(feature=>["depth_m","depth","elevation_m","elevation"].some(key=>Number.isFinite(Number(feature.properties[key]))));
 const hasTemporal=parsed.collection.features.some(feature=>["observed_at","timestamp","date","datetime"].some(key=>typeof feature.properties[key]==="string"&&String(feature.properties[key]).length>0));
 return{sourceManifestationId,parser:"SpatialGisCore/v1",state:"PASS",declaredCrs:"EPSG:4326",featureCount:parsed.accepted,exactFeatureIds:ids,duplicateFeatureIds:duplicates(ids),geometryTypes,capabilities:["vector","provenance",...(hasTerrain?["terrain"]:[]),...(hasTemporal?["temporal"]:[])],warnings:parsed.warnings}
}

export function SpatialDatasetIntake(){
 const[manifest,setManifest]=useState<UploadManifest|null>(null),[evidence,setEvidence]=useState<ParserEvidence[]>([]),[roles,setRoles]=useState<Record<string,SpatialDatasetRole>>({}),[preset,setPreset]=useState<AnalysisPresetId>("topology_review"),[busy,setBusy]=useState(false);
 const baseDatasets=useMemo(()=>manifest?buildSpatialDatasets(manifest,evidence):[],[manifest,evidence]),datasets=useMemo(()=>assignDatasetRoles(baseDatasets,roles),[baseDatasets,roles]),preflight=useMemo(()=>manifest?evaluatePresetEligibility(preset,datasets):null,[manifest,preset,datasets]),receipt=useMemo(()=>manifest?buildCanonicalAnalysisReceipt(manifest,preset,datasets):null,[manifest,preset,datasets]);
 const ingest=async(files:File[])=>{setBusy(true);try{const hashed=await Promise.all(files.map(async file=>({file,sha256:await sha256(file)}))),nextManifest=buildUploadManifest(hashed.map(({file,sha256:hash})=>({path:file.name,size:file.size,sha256:hash}))),nextEvidence:ParserEvidence[]=[];for(const{file}of hashed){const row=nextManifest.manifestations.find(item=>item.path===file.name&&!nextEvidence.some(entry=>entry.sourceManifestationId===item.sourceManifestationId));if(!row)continue;const parsed=await parserEvidence(file,row.sourceManifestationId);if(parsed)nextEvidence.push(parsed)}setManifest(nextManifest);setEvidence(nextEvidence);setRoles({})}finally{setBusy(false)}};
 return <section style={{display:"grid",gap:10,marginBottom:16,padding:12,border:"1px solid #1b3530",background:"#091411"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><strong style={{display:"block",fontSize:12}}>Dataset intake &amp; preflight</strong><span style={{display:"block",marginTop:3,color:"#78958d",fontSize:9}}>Manifest every source first. Sidecars group only by shared basename. Containers, rasters and GeoPackage fail closed until their adapters pass.</span></div>{manifest&&<Button variant="ghost" size="sm" onClick={()=>{setManifest(null);setEvidence([]);setRoles({})}}>Clear intake</Button>}</div>
  <FileDropzone accept={accepted} maxFiles={24} onFilesSelected={ingest} disabled={busy} title={busy?"Building source manifest…":"Upload spatial source manifestations"} subtitle="GeoJSON, KML, CSV, Shapefile sidecars, ZIP/KMZ, GeoTIFF, GeoPackage"/>
  {manifest&&<><div style={{display:"flex",gap:8,flexWrap:"wrap",fontSize:9}}><Badge variant={manifest.duplicatePaths.length?"warning":"secondary"}>manifest {manifest.manifestId}</Badge><span>{manifest.arithmetic.uploaded} uploaded</span><span>{manifest.groups.length} datasets/groups</span><span>{manifest.arithmetic.duplicates} duplicate paths</span></div>
  <div style={{display:"grid",gap:6}}>{datasets.map(dataset=><div key={dataset.runtimeDatasetId} style={{display:"grid",gridTemplateColumns:"minmax(180px,1fr) 120px 130px auto",gap:8,alignItems:"center",padding:8,border:"1px solid #142722",fontSize:9}}><div><code>{dataset.runtimeDatasetId}</code><div style={{color:"#78958d",marginTop:3}}>{dataset.format} · {dataset.declaredCrs} · {dataset.sourceManifestationIds.length} source manifestation(s)</div></div><Badge variant={dataset.parserState==="PASS"?"success":dataset.parserState==="FAIL"?"destructive":"warning"}>{dataset.parserState}</Badge><select aria-label={`Role for ${dataset.runtimeDatasetId}`} value={dataset.role} onChange={event=>setRoles(current=>({...current,[dataset.runtimeDatasetId]:event.target.value as SpatialDatasetRole}))} style={{minHeight:36,background:"#07100f",color:"#d7e7e1",border:"1px solid #31594e"}}><option>UNASSIGNED</option><option>PRIMARY</option><option>COMPARISON</option><option>AOI</option><option>REFERENCE</option><option>RASTER</option></select><span>{dataset.featureCount??"—"} features</span>{dataset.warnings.length>0&&<div style={{gridColumn:"1/-1",color:"#f1ca71"}}>{dataset.warnings.join(" · ")}</div>}</div>)}</div>
  <div style={{display:"grid",gridTemplateColumns:"minmax(180px,260px) 1fr",gap:8,alignItems:"center"}}><select aria-label="Analysis preset" value={preset} onChange={event=>setPreset(event.target.value as AnalysisPresetId)} style={{minHeight:38,background:"#07100f",color:"#d7e7e1",border:"1px solid #31594e",padding:"0 8px"}}>{SPATIAL_ANALYSIS_PRESETS.map(item=><option key={item.id} value={item.id}>{item.id}</option>)}</select><div><Badge variant={preflight?.state==="PASS"?"success":"warning"}>{preflight?.state??"BLOCKED"}</Badge><span style={{marginLeft:8,fontSize:9,color:"#78958d"}}>{preflight?.issues.length??0} preflight issue(s) · receipt {receipt?.receiptKey}</span></div></div>
  {preflight&&preflight.issues.length>0&&<ul style={{margin:0,paddingLeft:18,color:"#d8b66d",fontSize:9}}>{preflight.issues.map((issue,index)=><li key={`${issue.code}:${issue.datasetId??index}`}>{issue.code}: {issue.detail}</li>)}</ul>}</>}
 </section>
}