import { buildSkywatcherSpatialArtifact, buildSurfaceSampleReceipt, validateSurfaceManifest } from "./spatialSurfaceArtifact";

const surface=(overrides:Record<string,unknown>={})=>({surfaceId:"surface-1",sourceManifestationSha256:"hash",horizontalCrs:"EPSG:4326",horizontalDatum:"WGS84",verticalDatum:"NAVD88",units:"m",width:100,height:100,resolutionX:10,resolutionY:10,noDataValue:-9999,band:1,...overrides}) as any;
const sample=(overrides:Record<string,unknown>={})=>({observationId:"O1",longitude:-66.0,latitude:18.4,sourceGeometryRef:"skywatcher:observation:O1",value:-123,state:"VALUE" as const,...overrides}) as any;

describe("Spiderweb surface and Skywatcher handoff",()=>{
  it("requires explicit source hash, CRS, horizontal datum and vertical datum",()=>{const result=validateSurfaceManifest(surface({sourceManifestationSha256:null,horizontalCrs:null,horizontalDatum:null,verticalDatum:null}));expect(result.state).toBe("BLOCKED");expect(result.issues).toContain("SOURCE_MANIFESTATION_HASH_REQUIRED");expect(result.issues).toContain("VERTICAL_DATUM_REQUIRED");});
  it("requires positive raster dimensions and resolution",()=>{const result=validateSurfaceManifest(surface({width:0,resolutionX:0}));expect(result.state).toBe("BLOCKED");expect(result.issues).toContain("VALID_WIDTH_REQUIRED");expect(result.issues).toContain("VALID_RESOLUTION_X_REQUIRED");});
  it("requires explicit NoData semantics and accepts numeric zero as a valid declaration",()=>{expect(validateSurfaceManifest(surface({noDataValue:"UNDECLARED"})).state).toBe("BLOCKED");expect(validateSurfaceManifest(surface({noDataValue:0})).state).toBe("PASS");});
  it("blocks sampling when the surface contract is incomplete",()=>{expect(buildSurfaceSampleReceipt(surface({verticalDatum:null}),[sample()]).state).toBe("BLOCKED");});
  it("closes value, NoData, outside and unresolved sample arithmetic",()=>{const receipt=buildSurfaceSampleReceipt(surface(),[sample(),sample({observationId:"O2",value:null,state:"NODATA"}),sample({observationId:"O3",value:null,state:"OUTSIDE"}),sample({observationId:"O4",value:null,state:"UNRESOLVED"})]);expect(receipt.sampleCount).toBe(4);expect(receipt.valueCount).toBe(1);expect(receipt.noDataCount).toBe(1);expect(receipt.outsideCount).toBe(1);expect(receipt.unresolvedCount).toBe(1);expect(receipt.state).toBe("PASS");});
  it("blocks duplicate observation IDs instead of merging them",()=>{const receipt=buildSurfaceSampleReceipt(surface(),[sample(),sample({longitude:-66.1})]);expect(receipt.state).toBe("BLOCKED");expect(receipt.duplicateObservationIds).toEqual(["O1"]);});
  it("blocks invalid WGS84 coordinates",()=>{expect(buildSurfaceSampleReceipt(surface(),[sample({latitude:99})]).state).toBe("BLOCKED");});
  it("blocks VALUE samples without finite values",()=>{expect(buildSurfaceSampleReceipt(surface(),[sample({value:null})]).state).toBe("BLOCKED");});
  it("blocks NoData/outside/unresolved states that carry numeric values",()=>{expect(buildSurfaceSampleReceipt(surface(),[sample({state:"NODATA",value:-9999})])).toMatchObject({state:"BLOCKED"});});
  it("keeps sample receipts deterministic for identical evidence",()=>{const a=buildSurfaceSampleReceipt(surface(),[sample()]);const b=buildSurfaceSampleReceipt(surface(),[sample()]);expect(a.fingerprint).toBe(b.fingerprint);});
  it("keeps Spiderweb geometry authority and Skywatcher observation identity authority separate",()=>{const artifact=buildSkywatcherSpatialArtifact(surface(),[sample()]);expect(artifact.geometryAuthority).toBe("SPIDERWEB");expect(artifact.observationIdentityAuthority).toBe("SKYWATCHER");expect(artifact.promotedAircraftIdentity).toBeFalse();expect(artifact.state).toBe("PASS");});
  it("never invents aircraft identity from surface or geometry evidence",()=>{const artifact=buildSkywatcherSpatialArtifact(surface(),[sample({observationId:"UNKNOWN-OBS"})]);expect(artifact.observationIds).toEqual(["UNKNOWN-OBS"]);expect(artifact.promotedAircraftIdentity).toBeFalse();});
});