export const PROGRAM_ACTIVITY_EVENT_VERSION = "PROGRAM_ACTIVITY_EVENT/v1" as const;
export type ActivityState = "NOW"|"NEXT"|"QUEUED"|"BLOCKED"|"COMPLETED"|"SUPERSEDED"|"CONTRADICTED"|"UNRESOLVED";
export type ActivityPriority = 0|1|2|3|4;
export interface ProgramActivityEvent {
  schema: typeof PROGRAM_ACTIVITY_EVENT_VERSION;
  eventId:string; producerId:string; functionId:string; eventType:string; title:string; detail:string; category:string;
  state:ActivityState; priority:ActivityPriority; scheduledAt:string|null; observedAt:string|null; canonicalRoute?:string;
  provenance:{sourceId:string;sourceType:"DECLARED_WORKFLOW"|"AUTHORITATIVE_RUNTIME"|"SOURCE_MANIFESTATION"|"FEDERATION_RECEIPT";sourceRef?:string;manifestationSha256?:string|null};
  source:"DECLARED"|"LIVE"; supersedesEventId?:string; conflictKey?:string;
}
export interface DeclaredActivity { id:string; phase:"NOW"|"NEXT"|"QUEUED"|"BLOCKED"; title:string; detail:string; category:string; href?:string }
const PREFIX="federation.programActivity.v1.";
const PRIORITY:Record<DeclaredActivity["phase"],ActivityPriority>={NOW:0,NEXT:1,QUEUED:2,BLOCKED:3};
const validRoute=(value?:string)=>!value||(/^\/(?!\/)/.test(value)&&!value.includes("://"));
const validIso=(value:string|null)=>value===null||(typeof value==="string"&&Number.isFinite(Date.parse(value)));
const canonical=(value:unknown):string=>Array.isArray(value)?"["+value.map(canonical).join(",")+"]":value&&typeof value==="object"?"{"+Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+":"+canonical(v)).join(",")+"}":JSON.stringify(value);
export function declaredEvents(producerId:string,items:readonly DeclaredActivity[]):ProgramActivityEvent[]{return items.map(item=>({schema:PROGRAM_ACTIVITY_EVENT_VERSION,eventId:`declared:${producerId}:${item.id}`,producerId,functionId:item.id,eventType:"DECLARED_WORKFLOW",title:item.title,detail:item.detail,category:item.category,state:item.phase,priority:PRIORITY[item.phase],scheduledAt:null,observedAt:null,canonicalRoute:validRoute(item.href)?item.href:undefined,provenance:{sourceId:`dashboard-declared:${producerId}:${item.id}`,sourceType:"DECLARED_WORKFLOW"},source:"DECLARED"}))}
export function validateProgramActivityEvent(event:ProgramActivityEvent):string[]{const errors:string[]=[];if(event.schema!==PROGRAM_ACTIVITY_EVENT_VERSION)errors.push("schema");if(!event.eventId)errors.push("eventId");if(!event.producerId)errors.push("producerId");if(!event.functionId)errors.push("functionId");if(!event.eventType)errors.push("eventType");if(!event.title)errors.push("title");if(!event.category)errors.push("category");if(!Number.isInteger(event.priority)||event.priority<0||event.priority>4)errors.push("priority");if(!validIso(event.scheduledAt))errors.push("scheduledAt");if(!validIso(event.observedAt))errors.push("observedAt");if(!validRoute(event.canonicalRoute))errors.push("canonicalRoute");if(!event.provenance?.sourceId||!event.provenance?.sourceType)errors.push("provenance");return errors}
export function readLiveProgramActivity(producerId:string,storage:Pick<Storage,"getItem">=localStorage):ProgramActivityEvent[]{try{const raw=storage.getItem(PREFIX+producerId);if(!raw)return[];const parsed=JSON.parse(raw);if(!Array.isArray(parsed))return[];return parsed.filter((event:any)=>event?.producerId===producerId&&event?.source==="LIVE"&&validateProgramActivityEvent(event).length===0)}catch{return[]}}
export function appendProgramActivityEvent(event:ProgramActivityEvent,storage:Pick<Storage,"getItem"|"setItem">=localStorage){const errors=validateProgramActivityEvent(event);if(event.source!=="LIVE")errors.push("source");if(errors.length)throw new Error("INVALID_PROGRAM_ACTIVITY_EVENT:"+errors.join(","));const rows=readLiveProgramActivity(event.producerId,storage as Storage);const existing=rows.find(row=>row.eventId===event.eventId);if(existing){if(canonical(existing)===canonical(event))return false;throw new Error("PROGRAM_ACTIVITY_EVENT_ID_COLLISION")}storage.setItem(PREFIX+event.producerId,JSON.stringify([...rows,event]));return true}
const eventTime=(event:ProgramActivityEvent)=>event.observedAt??event.scheduledAt??"";
export function mergeProgramActivity(producerId:string,declared:readonly DeclaredActivity[],live:readonly ProgramActivityEvent[],nowMs=Date.now(),staleAfterMs=7*86400000){const liveRows=live.filter(event=>event.producerId===producerId&&event.source==="LIVE"&&validateProgramActivityEvent(event).length===0);const combined=[...declaredEvents(producerId,declared),...liveRows];const byId=new Map<string,ProgramActivityEvent>();for(const event of combined){const prior=byId.get(event.eventId);if(!prior)byId.set(event.eventId,event);else if(canonical(prior)!==canonical(event))byId.set(event.eventId,{...prior,state:"UNRESOLVED",detail:prior.detail+" · event ID collision"})}const rows=[...byId.values()];const superseded=new Set(rows.map(event=>event.supersedesEventId).filter(Boolean) as string[]);const groups=new Map<string,ProgramActivityEvent[]>();for(const event of rows)groups.set(event.functionId,[...(groups.get(event.functionId)||[]),event]);const output:Array<ProgramActivityEvent&{phase:ActivityState;href?:string}>=[];for(const group of groups.values()){const candidates=group.filter(event=>event.source==="LIVE"&&!superseded.has(event.eventId)).sort((a,b)=>eventTime(b).localeCompare(eventTime(a))||a.priority-b.priority||a.eventId.localeCompare(b.eventId));const chosen=candidates[0]||group.find(event=>event.source==="DECLARED");if(!chosen)continue;const tied=candidates.filter(event=>eventTime(event)===eventTime(chosen)&&event.priority===chosen.priority);const signatures=new Set(tied.map(event=>[event.state,event.title,event.canonicalRoute,event.eventType,event.conflictKey||""].join("|")));let state:ActivityState=tied.length>1&&signatures.size>1?"UNRESOLVED":chosen.state;if(chosen.source==="LIVE"&&chosen.observedAt&&!["COMPLETED","SUPERSEDED"].includes(state)&&nowMs-Date.parse(chosen.observedAt)>staleAfterMs)state="UNRESOLVED";output.push({...chosen,state,phase:state,href:chosen.canonicalRoute})}return output.sort((a,b)=>a.priority-b.priority||eventTime(a).localeCompare(eventTime(b))||a.functionId.localeCompare(b.functionId)||a.eventId.localeCompare(b.eventId))}
export function verifyCanonicalRoutes(events:readonly Pick<ProgramActivityEvent,"eventId"|"canonicalRoute">[],routePaths:readonly string[]){const allowed=new Set(routePaths);return events.filter(event=>event.canonicalRoute&&!allowed.has(event.canonicalRoute)).map(event=>({eventId:event.eventId,route:event.canonicalRoute as string}))}
