"""Contract/finance layer scoring for SpiderWeb.

Consumes artifacts generated by the moneysweep-pr adapter and produces a
scored SpiderWeb overlay. This module does not import moneysweep-pr.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from datetime import datetime, timezone
import csv
import json
import math
from pathlib import Path
from typing import Any, Iterable

from readiness.contract_finance_manifest_gate import (
    ContractFinanceManifestGateError,
    validate_contract_finance_manifest,
)

REQUIRED_INPUTS = (
    "contract_awards.geojson",
    "financial_flows.geojson",
    "municipality_funding_density.csv",
    "contract_finance_ingest_report.json",
)

OUTPUT_OVERLAY = "contract_finance_scored_overlay.geojson"
OUTPUT_REPORT = "contract_finance_layer_report.json"


class ContractFinanceLayerError(ValueError):
    """Raised when the contract/finance layer cannot be scored safely."""


def _load_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ContractFinanceLayerError(f"missing required file: {path.name}") from exc
    except json.JSONDecodeError as exc:
        raise ContractFinanceLayerError(f"invalid JSON in {path.name}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ContractFinanceLayerError(f"{path.name} must contain a JSON object")
    return payload


def _load_feature_collection(path: Path) -> list[dict[str, Any]]:
    payload = _load_json(path)
    if payload.get("type") != "FeatureCollection":
        raise ContractFinanceLayerError(f"{path.name} must be a GeoJSON FeatureCollection")
    features = payload.get("features")
    if not isinstance(features, list):
        raise ContractFinanceLayerError(f"{path.name}.features must be a list")
    return [feature for feature in features if isinstance(feature, dict)]


def _load_density(path: Path) -> dict[str, dict[str, Any]]:
    if not path.exists():
        raise ContractFinanceLayerError(f"missing required file: {path.name}")
    density: dict[str, dict[str, Any]] = {}
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            code = row.get("municipality_code") or "UNKNOWN"
            try:
                total_amount = float(row.get("total_amount") or 0)
                record_count = int(float(row.get("record_count") or 0))
            except ValueError as exc:
                raise ContractFinanceLayerError(f"invalid municipality density row for {code}") from exc
            density[code] = {
                "municipality_code": code,
                "municipality_name": row.get("municipality_name") or "UNKNOWN",
                "total_amount": total_amount,
                "record_count": record_count,
            }
    return density


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        result = float(value)
    except (TypeError, ValueError):
        return default
    return result if math.isfinite(result) else default


def _parse_date(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _amount_score(amount: float, max_amount: float) -> float:
    if amount <= 0 or max_amount <= 0:
        return 0.0
    return min(1.0, math.log1p(amount) / math.log1p(max_amount))


def _entity_convergence(entity_id: str, entity_counts: Counter[str]) -> float:
    if not entity_id:
        return 0.0
    count = entity_counts.get(entity_id, 0)
    if count <= 1:
        return 0.35
    if count == 2:
        return 0.70
    return 1.0


def _municipal_density_score(code: str, density: dict[str, dict[str, Any]], max_total: float) -> float:
    if not code or code not in density or max_total <= 0:
        return 0.0
    return min(1.0, _safe_float(density[code].get("total_amount")) / max_total)


def _temporal_pulse(date_value: Any, now: datetime) -> float:
    parsed = _parse_date(date_value)
    if parsed is None:
        return 0.0
    age_days = max(0.0, (now - parsed).total_seconds() / 86400.0)
    if age_days <= 365:
        return 1.0
    if age_days <= 730:
        return 0.55
    return 0.20


def _tier(score: float) -> str:
    if score >= 0.75:
        return "T1"
    if score >= 0.55:
        return "T2"
    if score >= 0.35:
        return "T3"
    return "T4"


def _score_features(features: list[dict[str, Any]], density: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    now = datetime.now(timezone.utc)
    entity_counts = Counter()
    for feature in features:
        props = feature.get("properties") or {}
        if props.get("entity_id"):
            entity_counts[str(props["entity_id"])] += 1

    max_amount = max((_safe_float((f.get("properties") or {}).get("amount")) for f in features), default=0.0)
    max_muni_total = max((_safe_float(row.get("total_amount")) for row in density.values()), default=0.0)
    scored: list[dict[str, Any]] = []

    for feature in features:
        props = dict(feature.get("properties") or {})
        code = str(props.get("municipality_code") or "UNKNOWN")
        entity_id = str(props.get("entity_id") or "")
        amount = _safe_float(props.get("amount"))
        components = {
            "amount_weight": _amount_score(amount, max_amount),
            "entity_convergence": _entity_convergence(entity_id, entity_counts),
            "municipal_density": _municipal_density_score(code, density, max_muni_total),
            "temporal_funding_pulse": _temporal_pulse(props.get("date"), now),
        }
        score = round(
            0.25 * components["amount_weight"]
            + 0.30 * components["entity_convergence"]
            + 0.25 * components["municipal_density"]
            + 0.20 * components["temporal_funding_pulse"],
            4,
        )
        tier = _tier(score)
        props.update(
            {
                "source_layer": "contract_finance",
                "spiderweb_score": score,
                "score_components": components,
                "evidence_tier": tier,
                "review_status": "accepted" if tier in {"T1", "T2"} else "manual_review",
            }
        )
        scored.append({"type": "Feature", "geometry": feature.get("geometry"), "properties": props})
    return sorted(scored, key=lambda f: (-_safe_float((f.get("properties") or {}).get("spiderweb_score")), str((f.get("properties") or {}).get("record_id"))))


def _write_geojson(path: Path, features: Iterable[dict[str, Any]]) -> None:
    payload = {
        "type": "FeatureCollection",
        "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:EPSG::4326"}},
        "features": list(features),
    }
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def _summarize(
    features: list[dict[str, Any]],
    ingest_report: dict[str, Any],
    input_dir: Path,
    manifest_report: dict[str, Any] | None = None,
) -> dict[str, Any]:
    by_tier = Counter()
    by_type = Counter()
    by_muni: dict[str, dict[str, Any]] = defaultdict(lambda: {"record_count": 0, "total_amount": 0.0})
    for feature in features:
        props = feature.get("properties") or {}
        by_tier[str(props.get("evidence_tier") or "UNKNOWN")] += 1
        by_type[str(props.get("feature_type") or "unknown")] += 1
        code = str(props.get("municipality_code") or "UNKNOWN")
        by_muni[code]["record_count"] += 1
        by_muni[code]["total_amount"] += _safe_float(props.get("amount"))
        by_muni[code]["municipality_name"] = props.get("municipality_name") or "UNKNOWN"

    # Centinelas pre-officialization provenance: how much of this overlay derives
    # from centinelas-pr FINANCIAL/POLITICAL signals routed through the MoneySweep
    # anchor. Counted directly from the scored features (robust to producer report
    # drift) and cross-referenced against the producer's own ingest-report block.
    centinelas_features = [
        f for f in features
        if str((f.get("properties") or {}).get("source_id")) == "centinelas-pr"
    ]
    centinelas_located = sum(
        1 for f in centinelas_features
        if (f.get("properties") or {}).get("municipality_code")
    )
    centinelas_provenance: dict[str, Any] = {
        "feature_count": len(centinelas_features),
        "located_feature_count": centinelas_located,
    }
    if isinstance(ingest_report.get("centinelas_pre_official"), dict):
        centinelas_provenance["producer_reported"] = ingest_report["centinelas_pre_official"]

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "input_dir": str(input_dir),
        "producer": ingest_report.get("producer"),
        "export_contract_version": ingest_report.get("export_contract_version"),
        "status": "READY" if features else "EMPTY",
        "record_count": len(features),
        "by_tier": dict(sorted(by_tier.items())),
        "by_feature_type": dict(sorted(by_type.items())),
        "by_municipality": dict(sorted(by_muni.items())),
        "centinelas_pre_official": centinelas_provenance,
        "score_features": ["entity_convergence", "municipal_density", "temporal_funding_pulse"],
        "outputs": {"scored_overlay": OUTPUT_OVERLAY, "layer_report": OUTPUT_REPORT},
    }
    if manifest_report is not None:
        report["artifact_manifest_gate"] = {
            "status": manifest_report["status"],
            "producer_repository": manifest_report.get("producer_repository"),
            "producer_commit": manifest_report.get("producer_commit"),
            "artifact_count": manifest_report.get("artifact_count"),
            "required_artifact_count": manifest_report.get("required_artifact_count"),
        }
    return report


def build_contract_finance_layer(
    input_dir: str | Path,
    output_dir: str | Path | None = None,
    *,
    artifact_manifest: str | Path | None = None,
) -> dict[str, Any]:
    """Build the scored SpiderWeb contract/finance overlay from adapter outputs."""

    root = Path(input_dir)
    out = Path(output_dir) if output_dir else root
    out.mkdir(parents=True, exist_ok=True)

    manifest_report: dict[str, Any] | None = None
    if artifact_manifest is not None:
        try:
            manifest_report = validate_contract_finance_manifest(artifact_manifest)
        except ContractFinanceManifestGateError as exc:
            raise ContractFinanceLayerError(f"artifact manifest gate failed: {exc}") from exc

    missing = [name for name in REQUIRED_INPUTS if not (root / name).exists()]
    if missing:
        raise ContractFinanceLayerError(f"missing contract/finance adapter outputs: {missing}")

    awards = _load_feature_collection(root / "contract_awards.geojson")
    flows = _load_feature_collection(root / "financial_flows.geojson")
    density = _load_density(root / "municipality_funding_density.csv")
    ingest_report = _load_json(root / "contract_finance_ingest_report.json")

    features = _score_features([*awards, *flows], density)
    _write_geojson(out / OUTPUT_OVERLAY, features)
    report = _summarize(features, ingest_report, root, manifest_report)
    (out / OUTPUT_REPORT).write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    return report
