"""Contract/finance layer scoring for SpiderWeb.

Consumes artifacts generated by the Contract-Sweeper adapter and produces a
scored SpiderWeb overlay. This module does not import Contract-Sweeper.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from datetime import datetime, timezone
import csv
import json
import math
from pathlib import Path
from typing import Any, Iterable

REQUIRED_INPUTS = (
    "contract_awards.geojson",
    "financial_flows.geojson",
    "municipality_funding_density.csv",
    "contract_finance_ingest_report.json",
)

OUTPUT_OVERLAY = "contract_finance_scored_overlay.geojson"
OUTPUT_REPORT = "contract_finance_layer_report.json"


class ContractFinanceLayerError(ValueError):
    """Raised when the contract/finance layer cannot be scored safely."""


def _load_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ContractFinanceLayerError(f"missing required file: {path.name}") from exc
    except json.JSONDecodeError as exc:
        raise ContractFinanceLayerError(f"invalid JSON in {path.name}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ContractFinanceLayerError(f"{path.name} must contain a JSON object")
    return payload


def _load_feature_collection(path: Path) -> list[dict[str, Any]]:
    payload = _load_json(path)
    if payload.get("type") != "FeatureCollection":
        raise ContractFinanceLayerError(f"{path.name} must be a GeoJSON FeatureCollection")
    features = payload.get("features")
    if not isinstance(features, list):
        raise ContractFinanceLayerError(f"{path.name}.features must be a list")
    return [feature for feature in features if isinstance(feature, dict)]


def _load_density(path: Path) -> dict[str, dict[str, Any]]:
    if not path.exists():
        raise ContractFinanceLayerError(f"missing required file: {path.name}")
    density: dict[str, dict[str, Any]] = {}
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            code = row.get("municipality_code") or "UNKNOWN"
            try:
                total_amount = float(row.get("total_amount") or 0)
                record_count = int(float(row.get("record_count") or 0))
            except ValueError as exc:
                raise ContractFinanceLayerError(f"invalid municipality density row for {code}") from exc
            density[code] = {
                "municipality_code": code,
                "municipality_name": row.get("municipality_name") or "UNKNOWN",
                "total_amount": total_amount,
                "record_count": record_count,
            }
    return density


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        result = float(value)
    except (TypeError, ValueError):
        return default
    return result if math.isfinite(result) else default


def _parse_date(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _amount_score(amount: float, max_amount: float) -> float:
    if amount <= 0 or max_amount <= 0:
        return 0.0
    return min(1.0, math.log1p(amount) / math.log1p(max_amount))


def _entity_convergence(entity_id: str, entity_counts: Counter[str]) -> float:
    if not entity_id:
        return 0.0
    count = entity_counts.get(entity_id, 0)
    if count <= 1:
        return 0.35
    if count == 2:
        return 0.70
    return 1.0


def _municipal_density_score(code: str, density: dict[str, dict[str, Any]], max_total: float) -> float:
    if not code or code not in density or max_total <= 0:
        return 0.0
    return min(1.0, _safe_float(density[code].get("total_amount")) / max_total)


def _temporal_pulse(date_value: Any, now: datetime) -> float:
    parsed = _parse_date(date_value)
    if parsed is None:
        return 0.0
    age_days = max(0.0, (now - parsed).total_seconds() / 86400.0)
    if age_days <= 365:
        return 1.0
    if age_days <= 730:
        return 0.55
    return 0.20


def _tier(score: float) -> str:
    if score >= 0.75:
        return "T1"
    if score >= 0.55:
        return "T2"
    if score >= 0.35:
        return "T3"
    return "T4"
