export type SpatialSourceFormat="geojson"|"json"|"kml"|"csv"|"shapefile"|"kmz"|"zip"|"geotiff"|"gpkg"|"unknown";
export type SpatialDatasetRole="PRIMARY"|"COMPARISON"|"AOI"|"REFERENCE"|"RASTER"|"UNASSIGNED";
export type SourceManifestation={sourceManifestationId:string;path:string;size:number;sha256:string|null;format:SpatialSourceFormat;containerId:string|null;basename:string;sidecarKind:string|null};
export type UploadManifest={schema:"spiderweb-upload-manifest/v1";manifestId:string;manifestations:SourceManifestation[];groups:Array<{groupId:string;kind:"single"|"shapefile_bundle"|"container";manifestationIds:string[];state:"READY"|"BLOCKED_PARTIAL"|"PRESERVED_CONTAINER";reason:string|null}>;arithmetic:{uploaded:number;grouped:number;ungrouped:number;duplicates:number};duplicatePaths:string[]};
export type ParserEvidence={sourceManifestationId:string;parser:string;state:"PASS"|"BLOCKED"|"FAIL";declaredCrs?:string|null;featureCount?:number;exactFeatureIds?:string[];duplicateFeatureIds?:string[];geometryTypes?:string[];capabilities?:string[];warnings?:string[];error?:string|null};
export type SpatialDataset={schema:"spiderweb-spatial-dataset/v1";runtimeDatasetId:string;sourceManifestationIds:string[];sourceIdsAreRuntimeIds:false;format:SpatialSourceFormat;role:SpatialDatasetRole;declaredCrs:string;parserState:"PASS"|"BLOCKED"|"FAIL";capabilities:string[];featureCount:number|null;exactFeatureIds:string[];duplicateFeatureIds:string[];geometryTypes:string[];provenance:{raw:{manifestationIds:string[]};normalized:{state:"AVAILABLE"|"UNAVAILABLE";parser:string|null};canonical:{state:"NOT_PROMOTED"|"ELIGIBLE";reason:string}};warnings:string[]};
export type AnalysisPresetId="topology_review"|"exact_id_difference"|"source_equivalence"|"terrain_bathymetry"|"temporal_comparison";
export type PreflightIssue={code:string;severity:"BLOCK"|"WARN";datasetId?:string;detail:string};
export type PreflightResult={schema:"spiderweb-analysis-preflight/v1";presetId:AnalysisPresetId;state:"PASS"|"BLOCKED";issues:PreflightIssue[];eligibleDatasetIds:string[];arithmetic:{inputDatasets:number;eligible:number;blocked:number}};
const sidecars=new Set(["shp","shx","dbf","prj","cpg"]),required=new Set(["shp","shx","dbf"]);
const norm=(p:string)=>p.trim().replace(/\\/g,"/").replace(/^\.\//,"");
const ext=(p:string)=>{const l=p.split("/").pop()??p,i=l.lastIndexOf(".");return i<0?"":l.slice(i+1).toLowerCase()};
const base=(p:string)=>{p=norm(p);const l=p.split("/").pop()??p,i=l.lastIndexOf("."),s=i<0?l:l.slice(0,i),parent=p.includes("/")?p.slice(0,p.lastIndexOf("/")+1):"";return parent+s};
export function classifySpatialSource(path:string){const e=ext(path);if(e==="geojson")return{format:"geojson" as const,sidecarKind:null};if(e==="json")return{format:"json" as const,sidecarKind:null};if(e==="kml")return{format:"kml" as const,sidecarKind:null};if(e==="csv")return{format:"csv" as const,sidecarKind:null};if(sidecars.has(e))return{format:"shapefile" as const,sidecarKind:e};if(e==="kmz")return{format:"kmz" as const,sidecarKind:null};if(e==="zip")return{format:"zip" as const,sidecarKind:null};if(e==="tif"||e==="tiff")return{format:"geotiff" as const,sidecarKind:null};if(e==="gpkg")return{format:"gpkg" as const,sidecarKind:null};return{format:"unknown" as const,sidecarKind:null}}
function sid(path:string,size:number,sha?:string|null){return sha?`sha256:${sha.toLowerCase()}`:`unhashed:${norm(path)}:${size}`}
function sort(v:any):any{return Array.isArray(v)?v.map(sort):v&&typeof v==="object"?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,sort(x)])):v}
function key(v:any){const s=JSON.stringify(sort(v));let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return`fnv1a32:${(h>>>0).toString(16).padStart(8,"0")}`}
export function buildUploadManifest(files:Array<{path:string;size:number;sha256?:string|null;containerId?:string|null}>):UploadManifest{
 const counts=new Map<string,number>();const manifestations=files.map(f=>{const path=norm(f.path),c=classifySpatialSource(path),raw=sid(path,f.size,f.sha256),n=(counts.get(raw)??0)+1;counts.set(raw,n);return{sourceManifestationId:n===1?raw:`${raw}:occurrence:${n}`,path,size:f.size,sha256:f.sha256?.toLowerCase()??null,format:c.format,containerId:f.containerId??null,basename:base(path),sidecarKind:c.sidecarKind}});
 const pc=new Map<string,number>();manifestations.forEach(r=>pc.set(r.path,(pc.get(r.path)??0)+1));const duplicatePaths=[...pc].filter(([,n])=>n>1).map(([p])=>p).sort(),used=new Set<string>(),groups:UploadManifest["groups"]=[];
 [...new Set(manifestations.filter(r=>r.format==="shapefile").map(r=>r.basename))].sort().forEach(b=>{const rows=manifestations.filter(r=>r.format==="shapefile"&&r.basename===b),kinds=new Set(rows.map(r=>r.sidecarKind).filter(Boolean)),missing=[...required].filter(k=>!kinds.has(k));rows.forEach(r=>used.add(r.sourceManifestationId));groups.push({groupId:`shapefile:${b}`,kind:"shapefile_bundle",manifestationIds:rows.map(r=>r.sourceManifestationId).sort(),state:missing.length?"BLOCKED_PARTIAL":"READY",reason:missing.length?`Missing required sidecars: ${missing.sort().join(", ")}`:null})});
 manifestations.filter(r=>!used.has(r.sourceManifestationId)).forEach(r=>{used.add(r.sourceManifestationId);const container=r.format==="zip"||r.format==="kmz";groups.push({groupId:`${container?"container":"single"}:${r.sourceManifestationId}`,kind:container?"container":"single",manifestationIds:[r.sourceManifestationId],state:container?"PRESERVED_CONTAINER":"READY",reason:container?"Container bytes preserved independently; members require an explicit container adapter.":null})});
 const material=manifestations.map(({path,size,sha256,format,containerId})=>({path,size,sha256,format,containerId}));
 return{schema:"spiderweb-upload-manifest/v1",manifestId:key(material),manifestations,groups,arithmetic:{uploaded:manifestations.length,grouped:used.size,ungrouped:Math.max(0,manifestations.length-used.size),duplicates:duplicatePaths.length},duplicatePaths}
}
export function buildSpatialDatasets(manifest:UploadManifest,evidence:ParserEvidence[]=[]):SpatialDataset[]{
 const byId=new Map(evidence.map(x=>[x.sourceManifestationId,x]));return manifest.groups.map((g,i)=>{const rows=g.manifestationIds.map(id=>manifest.manifestations.find(r=>r.sourceManifestationId===id)).filter(Boolean) as SourceManifestation[],format=rows[0]?.format??"unknown",ev=rows.map(r=>byId.get(r.sourceManifestationId)).filter(Boolean) as ParserEvidence[],warnings:string[]=[];
 if(g.state==="BLOCKED_PARTIAL")warnings.push(g.reason??"Partial source group.");if(format==="gpkg")warnings.push("GeoPackage adapter is BLOCKED until a parser contract is implemented and passes.");if(format==="zip"||format==="kmz")warnings.push("Archive/container preserved; member classification must be explicit before analysis.");if(format==="shapefile"&&g.state==="READY"&&!ev.length)warnings.push("Complete Shapefile sidecars found, but the specialized parser adapter has not supplied evidence.");if(format==="geotiff"&&!ev.length)warnings.push("Raster detected; analysis is blocked until the raster adapter contract supplies evidence.");
 let parserState:SpatialDataset["parserState"]=ev.some(x=>x.state==="FAIL")?"FAIL":ev.length&&ev.every(x=>x.state==="PASS")?"PASS":"BLOCKED";const crs=[...new Set(ev.map(x=>x.declaredCrs).filter(Boolean))] as string[];if(crs.length>1)warnings.push(`Mixed CRS evidence inside grouped dataset: ${crs.join(", ")}`);
 const exact=[...new Set(ev.flatMap(x=>x.exactFeatureIds??[]))].sort(),dups=[...new Set(ev.flatMap(x=>x.duplicateFeatureIds??[]))].sort(),geom=[...new Set(ev.flatMap(x=>x.geometryTypes??[]))].sort(),caps=[...new Set(ev.flatMap(x=>x.capabilities??[]))].sort(),fc=ev.map(x=>x.featureCount).filter((x):x is number=>typeof x==="number"),featureCount=fc.length?fc.reduce((a,b)=>a+b,0):null,eligible=parserState==="PASS"&&g.state!=="BLOCKED_PARTIAL"&&format!=="gpkg"&&!dups.length;
 return{schema:"spiderweb-spatial-dataset/v1",runtimeDatasetId:`runtime:${manifest.manifestId}:${i+1}`,sourceManifestationIds:[...g.manifestationIds],sourceIdsAreRuntimeIds:false,format,role:"UNASSIGNED",declaredCrs:crs.length===1?crs[0]:crs.length>1?"MIXED":"UNRESOLVED",parserState,capabilities:caps,featureCount,exactFeatureIds:exact,duplicateFeatureIds:dups,geometryTypes:geom,provenance:{raw:{manifestationIds:[...g.manifestationIds]},normalized:{state:parserState==="PASS"?"AVAILABLE":"UNAVAILABLE",parser:ev[0]?.parser??null},canonical:{state:eligible?"ELIGIBLE":"NOT_PROMOTED",reason:eligible?"Parser and identity preconditions pass; promotion still requires preflight.":warnings[0]??"Dataset is not eligible for canonical promotion."}},warnings:[...warnings,...ev.flatMap(x=>x.warnings??[])]}})
}
export const SPATIAL_ANALYSIS_PRESETS=[
 {id:"topology_review",requiredRoles:["PRIMARY"],requiredCapabilities:["vector"],minDatasets:1,maxDatasets:1,requireKnownCrs:false,requireExactIds:false},
 {id:"exact_id_difference",requiredRoles:["PRIMARY","COMPARISON"],requiredCapabilities:["vector"],minDatasets:2,maxDatasets:2,requireKnownCrs:true,requireExactIds:true},
 {id:"source_equivalence",requiredRoles:["PRIMARY","COMPARISON"],requiredCapabilities:["vector","provenance"],minDatasets:2,maxDatasets:2,requireKnownCrs:true,requireExactIds:true},
 {id:"terrain_bathymetry",requiredRoles:["PRIMARY"],requiredCapabilities:["terrain"],minDatasets:1,maxDatasets:2,requireKnownCrs:true,requireExactIds:false},
 {id:"temporal_comparison",requiredRoles:["PRIMARY","COMPARISON"],requiredCapabilities:["vector","temporal"],minDatasets:2,maxDatasets:2,requireKnownCrs:true,requireExactIds:true},
] as const;
export function assignDatasetRoles(ds:SpatialDataset[],a:Record<string,SpatialDatasetRole>){return ds.map(d=>({...d,role:a[d.runtimeDatasetId]??d.role}))}
export function evaluatePresetEligibility(id:AnalysisPresetId,ds:SpatialDataset[]):PreflightResult{
 const p=SPATIAL_ANALYSIS_PRESETS.find(x=>x.id===id);if(!p)throw new Error(`Unknown spatial analysis preset: ${id}`);const issues:PreflightIssue[]=[];if(ds.length<p.minDatasets||ds.length>p.maxDatasets)issues.push({code:"DATASET_COUNT",severity:"BLOCK",detail:`Preset ${id} requires ${p.minDatasets}-${p.maxDatasets} datasets; received ${ds.length}.`});
 for(const role of p.requiredRoles){const n=ds.filter(d=>d.role===role).length;if(!n)issues.push({code:"MISSING_ROLE",severity:"BLOCK",detail:`Missing required dataset role ${role}.`});if(n>1)issues.push({code:"AMBIGUOUS_ROLE_ASSIGNMENT",severity:"BLOCK",detail:`Multiple datasets are assigned role ${role}; ties are not resolved automatically.`})}
 ds.forEach(d=>{if(d.parserState!=="PASS")issues.push({code:"PARSER_NOT_PASS",severity:"BLOCK",datasetId:d.runtimeDatasetId,detail:`Parser state is ${d.parserState}.`});if(d.format==="gpkg")issues.push({code:"GEOPACKAGE_BLOCKED",severity:"BLOCK",datasetId:d.runtimeDatasetId,detail:"GeoPackage is intentionally blocked until its adapter contract passes."});if(d.declaredCrs==="MIXED")issues.push({code:"MIXED_CRS",severity:"BLOCK",datasetId:d.runtimeDatasetId,detail:"Grouped dataset has mixed CRS evidence."});if(p.requireKnownCrs&&(d.declaredCrs==="UNRESOLVED"||d.declaredCrs==="MIXED"))issues.push({code:"CRS_UNRESOLVED",severity:"BLOCK",datasetId:d.runtimeDatasetId,detail:`Preset ${id} requires a resolved CRS.`});if(p.requireExactIds&&!d.exactFeatureIds.length)issues.push({code:"EXACT_IDS_REQUIRED",severity:"BLOCK",datasetId:d.runtimeDatasetId,detail:"Exact stable feature IDs are required; name/nearest identity is forbidden."});if(d.duplicateFeatureIds.length)issues.push({code:"DUPLICATE_FEATURE_IDS",severity:"BLOCK",datasetId:d.runtimeDatasetId,detail:`Duplicate exact IDs: ${d.duplicateFeatureIds.join(", ")}`});const missing=p.requiredCapabilities.filter(c=>!d.capabilities.includes(c));if(missing.length)issues.push({code:"CAPABILITY_MISSING",severity:"BLOCK",datasetId:d.runtimeDatasetId,detail:`Missing capabilities: ${missing.join(", ")}`});const bad=d.geometryTypes.filter(t=>![ "Point","LineString","Polygon","MultiPoint","MultiLineString","MultiPolygon"].includes(t));if(bad.length)issues.push({code:"UNSUPPORTED_GEOMETRY",severity:"BLOCK",datasetId:d.runtimeDatasetId,detail:`Unsupported geometry: ${bad.join(", ")}`})});
 const block=issues.filter(x=>x.severity==="BLOCK"),eligible=ds.filter(d=>!block.some(x=>x.datasetId===d.runtimeDatasetId)).map(d=>d.runtimeDatasetId);return{schema:"spiderweb-analysis-preflight/v1",presetId:id,state:block.length?"BLOCKED":"PASS",issues,eligibleDatasetIds:eligible,arithmetic:{inputDatasets:ds.length,eligible:eligible.length,blocked:ds.length-eligible.length}}
}
export function buildCanonicalAnalysisReceipt(manifest:UploadManifest,presetId:AnalysisPresetId,datasets:SpatialDataset[]){
 const preflight=evaluatePresetEligibility(presetId,datasets),s=(x:boolean)=>(x?"PASS":"BLOCKED") as "PASS"|"BLOCKED",allParsed=datasets.every(d=>d.parserState==="PASS"),allNormalized=datasets.every(d=>d.provenance.normalized.state==="AVAILABLE"),run=preflight.state==="PASS";
 const graph=[{id:"manifest",stage:"INGEST_MANIFEST",dependsOn:[],state:s(!manifest.duplicatePaths.length)},{id:"classify",stage:"CLASSIFY_SOURCES",dependsOn:["manifest"],state:s(!manifest.duplicatePaths.length)},{id:"parse",stage:"PARSE_WITH_CONTRACTS",dependsOn:["classify"],state:s(allParsed)},{id:"normalize",stage:"NORMALIZE_WITHOUT_OVERWRITING_RAW",dependsOn:["parse"],state:s(allNormalized)},{id:"preflight",stage:"PREFLIGHT",dependsOn:["normalize"],state:preflight.state},{id:"analyze",stage:"ANALYZE",dependsOn:["preflight"],state:s(run)},{id:"receipt",stage:"RECEIPT",dependsOn:["analyze"],state:s(run)}];
 const material={manifestId:manifest.manifestId,presetId,sourceManifestationIds:manifest.manifestations.map(r=>r.sourceManifestationId).sort(),runtimeDatasetIds:datasets.map(r=>r.runtimeDatasetId).sort(),preflight:{state:preflight.state,issues:preflight.issues}};
 return{schema:"spiderweb-analysis-receipt/v1" as const,receiptKey:key(material),presetId,state:preflight.state,sourceManifestationIds:material.sourceManifestationIds,runtimeDatasetIds:material.runtimeDatasetIds,graph,preflight,conservation:{sourceManifestations:manifest.manifestations.length,datasets:datasets.length,canonicalPromotions:run?datasets.filter(d=>d.provenance.canonical.state==="ELIGIBLE").length:0,unexplainedResidue:manifest.arithmetic.ungrouped+manifest.duplicatePaths.length}}
}