name: Semgrep

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "23 3 * * 2"

permissions:
  contents: read

jobs:
  semgrep:
    uses: jotaele44/thehub-pr/.github/workflows/semgrep.yml@54f00e551c8660d83a657b54bf2a136dc4ebed42
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
