name: Semgrep

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "23 3 * * 2"

permissions:
  contents: read

jobs:
  semgrep:
    uses: jotaele44/thehub-pr/.github/workflows/semgrep.yml@2ee5f45222dc27d1166c539c864ecffd4ff97c3b
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
